# Generated by Django 5.1.7 on 2025-12-17 21:13

import django.db.models.deletion
import django.utils.timezone
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, default=invoices.models.Invoice.generate_invoice_number, max_length=100, null=True)),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_status', models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente de Pago', max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('invoice_quantity', models.IntegerField(blank=True, null=True)),
                ('invoice_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_discount_description', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
