# Generated by Django 5.1.7 on 2025-03-23 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery_name', models.CharField(max_length=100)),
                ('jewellery_quantity', models.IntegerField()),
                ('jewellery_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jewellery_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.jewelleryitem')),
                ('diamond_name', models.CharField(max_length=100)),
                ('diamond_shape', models.CharField(max_length=100)),
                ('diamond_color', models.CharField(max_length=100)),
                ('diamond_clarity', models.CharField(max_length=100)),
                ('diamond_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamond_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamond_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('invoices.jewelleryitem',),
        ),
        migrations.CreateModel(
            name='Emerald',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.jewelleryitem')),
                ('emerald_name', models.CharField(max_length=100)),
                ('emerald_color', models.CharField(max_length=100)),
                ('emerald_clarity', models.CharField(max_length=100)),
                ('emerald_carat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emerald_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emerald_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            bases=('invoices.jewelleryitem',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.jewelleryitem')),
                ('ring_name', models.CharField(max_length=100)),
                ('ring_size', models.CharField(max_length=100)),
                ('ring_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ring_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ring_type', models.CharField(max_length=100)),
            ],
            bases=('invoices.jewelleryitem',),
        ),
        migrations.CreateModel(
            name='InvoiceForItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_type', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('items', models.ManyToManyField(to='invoices.jewelleryitem')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceForMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('invoice_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
