# Generated by Django 5.1.7 on 2025-06-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, default='Cotización', max_length=100, null=True),
        ),
    ]
