# Generated by Django 5.1.7 on 2025-03-25 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdocumenttype_alter_client_document_number_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainOrBracelet',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.jewelleryitem')),
                ('chain_or_bracelet_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chain_or_bracelet_quality', models.CharField(max_length=100)),
                ('long', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric', models.CharField(max_length=100)),
            ],
            bases=('invoices.jewelleryitem',),
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_name', models.CharField(max_length=100)),
                ('stone_color', models.CharField(max_length=100)),
                ('stone_clarity', models.CharField(max_length=100)),
                ('stone_carat', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='emerald',
            name='jewelleryitem_ptr',
        ),
        migrations.RenameField(
            model_name='ring',
            old_name='ring_name',
            new_name='ring_quality',
        ),
        migrations.RenameField(
            model_name='ring',
            old_name='ring_price',
            new_name='ring_weight',
        ),
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='jewellery_price',
        ),
        migrations.RemoveField(
            model_name='jewelleryitem',
            name='jewellery_total',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='ring_total',
        ),
        migrations.AddField(
            model_name='invoiceforitem',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/client_signatures/'),
        ),
        migrations.AddField(
            model_name='invoiceforitem',
            name='invoice_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceforitem',
            name='invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceforitem',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/client_signatures/'),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='invoice_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='invoice_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jewelleryitem',
            name='certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ring',
            name='synthetic_stone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='items',
            field=models.ManyToManyField(blank=True, to='invoices.jewelleryitem'),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceForStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='uploads/client_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
                ('stone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.stone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ring',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='invoices.stone'),
        ),
        migrations.DeleteModel(
            name='Diamond',
        ),
        migrations.DeleteModel(
            name='Emerald',
        ),
    ]
