# Generated by Django 5.1.7 on 2025-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_chainorbracelet_stone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceforitem',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='invoices.jewelleryitem'),
        ),
    ]
