# Generated by Django 5.1.7 on 2025-07-07 19:18

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default=invoices.models.Invoice.generate_invoice_number, max_length=100, null=True),
        ),
    ]
