# Generated by Django 5.1.7 on 2025-05-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoiceforitem_items'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ring',
            name='jewelleryitem_ptr',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='stone',
        ),
        migrations.AlterField(
            model_name='invoiceforstone',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.stone'),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items', to='products.jewelleryitem'),
        ),
        migrations.DeleteModel(
            name='ChainOrBracelet',
        ),
        migrations.DeleteModel(
            name='JewelleryItem',
        ),
        migrations.DeleteModel(
            name='Ring',
        ),
        migrations.DeleteModel(
            name='Stone',
        ),
    ]
