# Generated by Django 5.1.7 on 2025-05-01 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_address_alter_client_document_number_and_more'),
        ('invoices', '0004_remove_ring_jewelleryitem_ptr_remove_ring_stone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceForCustomized',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_type', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_status', models.CharField(blank=True, max_length=100, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='uploads/client_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
