# Generated by Django 5.1.7 on 2025-11-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
