# Generated by Django 5.1.7 on 2025-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoiceforcustomized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceforcustomized',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforstone',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=100, null=True),
        ),
    ]
