# Generated by Django 5.1.7 on 2025-05-01 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoiceforcustomized_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceforcustomized',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='invoiceforitem',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='invoiceformaintenance',
            name='client_signature',
        ),
        migrations.RemoveField(
            model_name='invoiceforstone',
            name='client_signature',
        ),
    ]
