# Generated by Django 5.1.7 on 2025-05-01 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoiceforcustomized_client_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceforcustomized',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoiceforstone',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
