# Generated by Django 5.1.7 on 2025-05-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoiceforcustomized_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceforcustomized',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceforitem',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceformaintenance',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceforstone',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforcustomized',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente de Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforitem',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente de Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceformaintenance',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente de Pago', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceforstone',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Cancelado', 'Cancelado')], default='Pendiente de Pago', max_length=100, null=True),
        ),
    ]
