# Generated by Django 5.1.7 on 2025-12-17 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator])),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$')])),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], max_length=100, null=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
