# Generated by Django 5.1.7 on 2025-05-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientdocumenttype_alter_client_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('NIT', 'Número de Identificación Tributaria'), ('PAS', 'Pasaporte')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ClientDocumentType',
        ),
    ]
