# Generated by Django 5.1.7 on 2025-11-02 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
    ]
