# Generated by Django 5.1.7 on 2025-11-02 02:32

import clients.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document_number',
            field=models.CharField(default=clients.models.Client.generate_document_number, max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$')]),
        ),
    ]
