# Generated by Django 5.1.7 on 2025-12-17 21:13

import django.db.models.deletion
import django.utils.timezone
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('quote_number', models.CharField(default=quotes.models.Quote.generate_quote_number, max_length=100, unique=True)),
                ('quote_quantity', models.IntegerField(blank=True, null=True)),
                ('quote_product_type', models.CharField(choices=[('Anillo de Compromiso', 'Anillo de Compromiso'), ('Anillo de Matrimonio', 'Anillo de Matrimonio'), ('A medida', 'A medida'), ('Otro', 'Otro')], max_length=100)),
                ('quote_date', models.DateField(default=django.utils.timezone.now)),
                ('quote_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_description', models.TextField(blank=True, null=True)),
                ('quote_additional_notes', models.TextField(blank=True, null=True)),
                ('quote_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_discount_description', models.CharField(blank=True, max_length=100, null=True)),
                ('email_sent', models.BooleanField(blank=True, default=False, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
