# Generated by Django 5.1.7 on 2025-04-29 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_clientdocumenttype_alter_client_document_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_quantity', models.IntegerField(blank=True, null=True)),
                ('quote_date', models.DateField(blank=True, null=True)),
                ('quote_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quote_description', models.TextField(blank=True, null=True)),
                ('quote_details', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
        ),
    ]
