# Generated by Django 5.1.7 on 2025-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='mpijFTCId1', max_length=100, null=True, unique=True),
        ),
    ]
