# Generated by Django 5.1.7 on 2025-05-01 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWA77v', max_length=100, null=True, unique=True),
        ),
    ]
