# Generated by Django 5.1.7 on 2025-05-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_alter_quote_quote_number_alter_quote_quote_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_description',
            new_name='quote_additional_notes',
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWA2wH', max_length=100, null=True, unique=True),
        ),
    ]
