# Generated by Django 5.1.7 on 2025-05-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_rename_quote_description_quote_quote_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWAa7J', max_length=100, null=True, unique=True),
        ),
    ]
