# Generated by Django 5.1.7 on 2025-05-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_alter_quote_quote_details_alter_quote_quote_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote_details',
            new_name='quote_description',
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWAe8E', max_length=100, null=True, unique=True),
        ),
    ]
