# Generated by Django 5.1.7 on 2025-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_rename_quote_details_quote_quote_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_product_type',
            field=models.CharField(blank=True, choices=[('Anillo de Compromiso', 'Anillo de Compromiso'), ('Anillo de Matrimonio', 'Anillo de Matrimonio'), ('A medida', 'A medida'), ('Otro', 'Otro')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWARDX', max_length=100, null=True, unique=True),
        ),
    ]
