# Generated by Django 5.1.7 on 2025-05-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_quote_quote_product_type_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWAMCt', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_product_type',
            field=models.CharField(choices=[('Anillo de Compromiso', 'Anillo de Compromiso'), ('Anillo de Matrimonio', 'Anillo de Matrimonio'), ('A medida', 'A medida'), ('Otro', 'Otro')], max_length=100),
        ),
    ]
