# Generated by Django 5.1.7 on 2025-05-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0015_alter_quote_quote_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWARVd', max_length=100, null=True, unique=True),
        ),
    ]
