# Generated by Django 5.1.7 on 2025-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0016_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWAbI2', max_length=100, null=True, unique=True),
        ),
    ]
