# Generated by Django 5.1.7 on 2025-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWAy4g', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
