# Generated by Django 5.1.7 on 2025-05-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0019_alter_quote_quote_number_alter_quote_quote_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(blank=True, default='EWApBp', max_length=100, null=True, unique=True),
        ),
    ]
