# Generated by Django 5.1.7 on 2025-05-15 07:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0023_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
