# Generated by Django 5.1.7 on 2025-05-15 08:16

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0025_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(default=quotes.models.Quote.generate_quote_number, max_length=100, unique=True),
        ),
    ]
