# Generated by Django 5.1.7 on 2025-06-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0026_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
