# Generated by Django 5.1.7 on 2025-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0027_quote_quote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_discount_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
