# Generated by Django 5.1.7 on 2025-07-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0028_quote_quote_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
