# Generated by Django 5.1.7 on 2025-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0029_quote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
