# Generated by Django 5.1.7 on 2025-11-02 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_client_document_number'),
        ('quotes', '0030_quote_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
