# Generated by Django 5.1.7 on 2025-05-01 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jewellery_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jewellery_quantity', models.IntegerField(blank=True, null=True)),
                ('certificate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_color', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_clarity', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_carat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChainOrBracelet',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.jewelleryitem')),
                ('chain_or_bracelet_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chain_or_bracelet_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('long', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fabric', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('products.jewelleryitem',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('jewelleryitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.jewelleryitem')),
                ('ring_description', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_size', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_quality', models.CharField(blank=True, max_length=100, null=True)),
                ('ring_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('synthetic_stone', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/rings/')),
            ],
            bases=('products.jewelleryitem',),
        ),
    ]
