# Generated by Django 5.1.7 on 2025-05-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ring',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/rings/'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='ring_type',
            field=models.CharField(blank=True, choices=[('Anillo', 'Anillo de Compromiso'), ('Anillo', 'Anillo de Matrimonio mujer'), ('Anillo', 'Anillo de Matrimonio hombre'), ('Anillo', 'Anillo de Regalo mujer'), ('Anillo', 'Anillo de Regalo hombre')], max_length=100, null=True),
        ),
    ]
