# Generated by Django 5.1.7 on 2025-05-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_ring_image_alter_ring_ring_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stone',
            options={'verbose_name': 'Piedra', 'verbose_name_plural': 'Piedras'},
        ),
        migrations.RenameField(
            model_name='stone',
            old_name='stone_name',
            new_name='stone_description',
        ),
        migrations.AlterField(
            model_name='chainorbracelet',
            name='chain_or_bracelet_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jewelleryitem',
            name='certificate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='ring_quality',
            field=models.CharField(blank=True, choices=[('Oro amarillo 18k', 'Oro amarillo 18k'), ('Oro blanco 18k', 'Oro blanco 18k'), ('Oro rosa 18k', 'Oro rosa 18k'), ('Plata 950', 'Plata 950')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ring',
            name='ring_type',
            field=models.CharField(blank=True, choices=[('Anillo de Compromiso', 'Anillo de Compromiso'), ('Anillo de Matrimonio mujer', 'Anillo de Matrimonio mujer'), ('Anillo de Matrimonio hombre', 'Anillo de Matrimonio hombre'), ('Anillo de Regalo mujer', 'Anillo de Regalo mujer'), ('Anillo de Regalo hombre', 'Anillo de Regalo hombre')], max_length=100, null=True),
        ),
    ]
