# Generated by Django 5.1.7 on 2025-05-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_stone_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jewelleryitem',
            old_name='jewellery_name',
            new_name='jewellery_description',
        ),
        migrations.RemoveField(
            model_name='chainorbracelet',
            name='chain_or_bracelet_weight',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='ring_description',
        ),
        migrations.RemoveField(
            model_name='ring',
            name='ring_weight',
        ),
        migrations.RemoveField(
            model_name='stone',
            name='stone_description',
        ),
    ]
